version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=artem
      - POSTGRES_PASSWORD=weak_password
      - POSTGRES_DB=conferences
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local